### PR TITLE
small ordering tweak in HPC layout

### PR DESCRIPTION
**Pull request by ChristinaLK**
I think the title should always come first.

### CODE REVIEW

**Comment by ChristinaLK** [comment]
Ah. HMMM.

I don't think it looks too bad. What if I changed the header of additional links to h2?

**Comment by jmvera255** [comment]
Sure lets try that, but to keep things simplified, I would actually just remove the page.title part of this template and revise the layout file... I'll make the changes now

**Comment by ChristinaLK** [comment]
actually, I was going to say that it's fine as is.

**Comment by ChristinaLK** [comment]
I'll close this and we can revisit later.

**Pull request closed without merging**
