### PR TITLE
updating hpc singularity guide

### PR DESCRIPTION
**Pull request by ChristinaLK**

### CODE REVIEW

**Comment by ChristinaLK** [comment]
@psbritt hopefully this tag works. I can't assign you as a reviewer proper because you're not a member of the repo. 🤷‍♀️

**Comment by psbritt** [comment]
One note I'd make, assuming that most people will be using MPI when using a singularity container with the cluster, is how to properly utilize MPI with a singularity container.

https://sylabs.io/guides/3.8/user-guide/mpi.html

There are a couple of methods. I used "the hybrid container", in which a version of MPI must be present within the container also that will work in tandem with MPI on the host. I specifically had issues with this originally since the version of MPI I was using in the container was different from the one on the HPC, so I installed the version of MPI that was on the HPC into the container which worked. This can be done when creating the docker container before converting it to a singularity container.

Other than that, it looks good to me.

**Comment by ChristinaLK** [comment]
@psbritt THANK YOU, that is exactly the part of the guide I was least confident about. 🙏 

I'll add some more comments about this in the guide.

**Comment by ChristinaLK** [comment]
@psbritt one final question: do you load an MPI module before using the singularity container, then?

**Comment by psbritt** [comment]
Yes, you have to do this regardless of what container type you use.

**Comment by lmichael107** [comment]
@ChristinaLK ready to merge?

**Comment by ChristinaLK** [comment]
Waiting for a review from @jasoncpatton .

**Review by jasoncpatton — CHANGES_REQUESTED** [review]
LGTM

**Review by jasoncpatton — APPROVED** [review]

**Pull request merged**
