### PR TITLE
moving facilitation team to own page

### PR DESCRIPTION
**Pull request by ChristinaLK**
https://chtc.github.io/web-preview/preview-facilitation-page/

### CODE REVIEW

**Comment by ChristinaLK** [comment]
The pictures aren't rendering, but @rachellombardi can you give a review of the content?

**Comment by rachellombardi** [comment]
@ChristinaLK I think it's fine, as long as you're fine with: 
* Research Facilitator Manager --> sounds weird, I'd be more inclined to do "Research Facilitation Manager". If you would prefer this title over Lead RCF, let us know and we will start referring to you in formal emails with this title. 
* Zoom isn't capitalized. Also, previously there was a discussion about not using the word Zoom to not favor one online technology over another in text.

**Review by rachellombardi — APPROVED** [review]
As a last comment, I tend to capitalize "Facilitation team" since it's the official name of our team. But it's not necessary for others to do that.

**Review by CannonLock — APPROVED** [review]
LGTM, images are borked as it is a preview and the paths are different.

**Pull request merged**
