### PR TITLE
Passing arguments guide

### PR DESCRIPTION
**Pull request by xamberl**
Creates a new guide for passing arguments. Preview page here: https://chtc.github.io/web-preview/preview-xalim-pass-args-guide/uw-research-computing/htc-passing-arguments

### CODE REVIEW

**Review by ChristinaLK — COMMENTED** [review]
Discussed in person - will split into two guides!

**Comment by xamberl** [comment]
Part 1 of discussed changes, a basic scripting guide, can be previewed here: https://chtc.github.io/web-preview/preview-xalim-pass-args-guide/uw-research-computing/htc-basic-scripting

Note that the icons don't work in the web preview, but do work on my local preview.

**Comment by xamberl** [comment]
Part 2: https://chtc.github.io/web-preview/preview-xalim-pass-args-guide/uw-research-computing/htc-passing-arguments

**Review by ChristinaLK — APPROVED** [review]
let's merge!

**Pull request closed without merging**
