### PR TITLE
Update team page

### PR DESCRIPTION
**Pull request by CannonLock**
New Staff Page
Screen Shot 2021-06-22 at 11 51 35 AM
Screen Shot 2021-06-22 at 11 51 28 AM

### CODE REVIEW

**Comment by CannonLock** [comment]
Whoever reviews this is going to have to take a careful look at job_title in the _data/team.yml file for people. As I grabbed a lot of this information from other projects this is likely different for CHTC and needs to be changed.

**Review by ChristinaLK — COMMENTED** [review]
@lmichael107 should the CHTC team page only have UW-Madison based staff?

**Comment by lmichael107** [comment]
> @lmichael107 should the CHTC team page only have UW-Madison based staff?

Probably should include people like Brian, Cannon, etc., who contribute to CHTC's mission, but with proper attribution to Morgridge.

**Comment by bbockelm** [comment]
CHTC is a center at UW-Madison that includes Morgridge Research Computing as a partner.  We should include the full time staff in the Bockelman group as well.

**Comment by lmichael107** [comment]
Then we're in agreement! Let us know when you've got a new version to review, @CannonLock. Like you said, I imagine we'll need to look hard at job_title, etc., for each person before going live.

**Comment by CannonLock** [comment]
Will we be adding people such as Emile, Kent or Ian Ross? These people were not in the excel I have been going off of, but are in the CHTC team picture.

**Comment by bbockelm** [comment]
Yup, add them!

(Don't delay merging this to get it perfect though.)

**Comment by CannonLock** [comment]
If someone can look through the titles we can get this into production.

**Review by lmichael107 — APPROVED** [review]
Approving, so Cannon can solicit input from everyone, per Slack convo.

**Pull request merged**
