### PR TITLE
Use https for the webform locations.

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
I marked this as draft until I know that the webform works as is.

**Comment by bbockelm** [comment]
Would it be better to use a relative URL instead?

**Comment by matyasselmeci** [comment]
Does that work? It's an HTTP header, not a link.

**Comment by jmvera255** [comment]
although the Travis-CI says still pending, the check was actually completed successfully (see 'details')

**Pull request merged**
