### PR TITLE
Create transfer-data-researchdrive.md

### PR DESCRIPTION
**Pull request by ChristinaLK**

### CODE REVIEW

**Comment by jmvera255** [comment]
Can we change it so that it just for using with ResearchDrive? Users may have data in another file server (like someone from Botany) that can also potentially use smbclient for their file transfer

**Comment by ChristinaLK** [comment]
Fine w/ me.

**Comment by bbockelm** [comment]
Can we suggest people instead use `-k` to make this passwordless?  I dislike encouraging people to type in their password in a SSH session...

The downside here is using `-k` will break if they don't have a NetID -- but I'm personally OK with adding a sentence saying "drop `-k` if you don't login with Wisconsin NetID".

Also, we may want to consider better ways to download.  Here's a relevant StackOverflow post:

https://superuser.com/questions/856617/how-do-i-recursively-download-a-directory-using-smbclient

Note the last option - downloading all files in a directory as a tarball - appears quite powerful and would discourage folks from having many many files.

**Comment by jmvera255** [comment]
@bbockelm 
> Can we suggest people instead use `-k` to make this passwordless? I dislike encouraging people to type in their password in a SSH session...
> 
> The downside here is using `-k` will break if they don't have a NetID -- but I'm personally OK with adding a sentence saying "drop `-k` if you don't login with Wisconsin NetID".

This is my one concern as I think some people may be using smbclient to transfer data from sources other than ResearchDrive (I've actually been in communication with a user in this case). I am fine with this change as as long as we make it clear in the guide that `-k` should be dropped if their CHTC user credentials don't aligned with those of the file server that they are trying to access

**Comment by ChristinaLK** [comment]
thanks for the suggestions both @bbockelm and @jmvera255 . It may be a bit before I get to this, so changes to my changes are welcome.

**Comment by ChristinaLK** [comment]
@jmvera255 I added a note in the beginning about using this for other services - should we also rename the actual .md file with the guide? If so, what should it be called? 

@bbockelm did I say the right things about `-k`?

**Comment by jmvera255** [comment]
@ChristinaLK what's the "{: .term}" bit that is showing up in the rendered md file? can we remove that?

**Comment by bbockelm** [comment]
@jmvera255 - there are many different variants of Markdown, unfortunately.  The one used for the CHTC website will render that with a special CSS tag but the GitHub renderer doesn't understand the syntax (resulting in the visible `{: .term}`).

So, we can just ignore for now...

**Pull request merged**
