### PR TITLE
add GitHub button, center office hours text

### PR DESCRIPTION
**Pull request by jmvera255**
added a button with link to website GitHub repo, edited office hours text to set end time to 5pm and centered that text within the box

### CODE REVIEW

**Comment by ChristinaLK** [comment]
Waiting to see if we can reduce buttons from 4 to 3 somehow.

**Comment by jmvera255** [comment]
Screen Shot 2020-03-20 at 5 31 56 PM
See attached image for a look at the icon-only Twitter+GitHub button that is now in the pull request

**Comment by ChristinaLK** [comment]
I liked the "edit our website on Github" text, but this is definitely cleaner. Looks good to me!

**Comment by jmvera255** [comment]
cramming both the text and the icons into a single button/box was too much, the icons were too small to see
Screen Shot 2020-03-20 at 5 13 24 PM

**Comment by ChristinaLK** [comment]
Yeah, I like your modified version better.

**Pull request merged**
