### PR TITLE
Deleting old pages

### PR DESCRIPTION
**Pull request by ChristinaLK**

### CODE REVIEW

**Comment by ChristinaLK** [comment]
Don't merge until Lauren has had a chance to review!

**Review by lmichael107 — COMMENTED** [review]
Pages to archive and not publish:
DAGenv.md
chtcjobwrapper.md
chtcpolicy.md
chtcrun-transition.md
file-avail-gluster.md
hours.md
hpc-cluster-downtime.md
hpc-transition.md
os-transition.md
showcase.md

Keep?:
how-tos.md: This is our current how-tos menu list, right? Would deleting it break things.
other-resources: same as above

Pages to delete:
HTC-guides.md
MATLABandR.md
MPIuseguide.md
archived/HPCuseguide.md
archived/howto_overview.shtml
archived/inter-submit.shtml
file-avail-largdata-test.md
submit_variations.md
artofHTC.md

**Comment by CannonLock** [comment]
### Current State

+ is a article is a article not mentioned by Lauren but in this category
- is a article mentioned by Lauren and not in this category

Pages to archive and not publish:
- matlab-jobs.shtml +
- python-jobs.shtml +
- r-jobs.shtml +
- file-avail-largedata-test +

Pages to delete:
- file-avail-largdata-test.md -

**Comment by ChristinaLK** [comment]
@CannonLock I addressed all your comments by double-checking those guides, if you give an approving review, I can merge.

**Comment by CannonLock** [comment]
LGTM. Can confirm that none of the archived pages are published as expected.

**Review by CannonLock — APPROVED** [review]
LGTM.

**Pull request merged**
