### PR TITLE
Fixes to the CI scripts to handle deletions and symlinks

### PR DESCRIPTION
**Pull request by matyasselmeci**
(Also includes a Vagrantfile for testing.)

This does end up deleting a few files from the website that don't have corresponding sources. The list is:
```
README
TEMPLATE.shtml
allguides.shtml
cal.shtml
firstHPCuseguide.shtml
form.old.shtml
form_captcha.shtml
get-help-beta.shtml
helloworld.md
howto_overview_new.shtml
howto_overview_prev.shtml
hpc-overview-el7.shtml
inprogress/docker-build.html
inprogress/docker-jobs.html
inprogress/docker-test.html
opmetrics.shtml
presentations.shtml
user-meeting-registered.shtml
user-meeting.shtml
```
I didn't find any usages of these pages in the built website (except in the 'archived' and/or 'archive_html' directories).

### CODE REVIEW

**Comment by bbockelm** [comment]
Sorry - little chance I'm going to be able to review this closely.  I think we'll just have to merge and observe for issues...

**Comment by matyasselmeci** [comment]
@ChristinaLK , can you take a look at the list I posted in the description and see if I missed something?

**Comment by matyasselmeci** [comment]
Do we need helloworld.md itself, or do we need helloworld.shtml? That one's still going to be there: https://condor-websrv-06.cs.wisc.edu/helloworld.shtml

**Comment by matyasselmeci** [comment]
> Do we need helloworld.md itself, or do we need helloworld.shtml? That one's still going to be there: https://condor-websrv-06.cs.wisc.edu/helloworld.shtml

Sorry, you already mentioned that.

I'll merge and will double-check when the site gets updated a little later.

**Pull request merged**
