### PR TITLE
Make Miron's suggestions to the technologies page

### PR DESCRIPTION
**Pull request by CannonLock**

### CODE REVIEW

**Comment by CannonLock** [comment]
https://chtc.github.io/web-preview/preview-tech-update/technologies

**Review by jasoncpatton — APPROVED** [review]
Oh boy, looking at the old page, that's a lot of old cruft swept under the rug. But I think anyone coming to the CHTC page and clicking on Technologies are more interested in the whole package, not just chirp or DAGMan.

**Comment by jasoncpatton** [comment]
Does this obsolete #332?

**Review by jasoncpatton — COMMENTED** [review]
Trying to un-set as approved.

**Review by jasoncpatton — CHANGES_REQUESTED** [review]
Waiting for this to be converted to markdown

**Comment by CannonLock** [comment]
@jasoncpatton I am figuring out if this makes #332 obsolete. I will adjust that PR as that information become available.

**Comment by CannonLock** [comment]
Closes #332

**Review by jasoncpatton — APPROVED** [review]

**Comment by jasoncpatton** [comment]
@CannonLock I'll let you merge when you think it's ready but it looks good to me

**Pull request merged**
