### PR TITLE
HPC upgrade complete doc changes

### PR DESCRIPTION
**Pull request by jmvera255**
remove links and references to old HPC info and guides. @ChristinaLK @lmichael107 do we want to move old HPC docs to archive or keep them accessible?

### CODE REVIEW

**Review by ChristinaLK — APPROVED** [review]
We could also remove (?) or edit the HPC-transition document.

**Comment by ChristinaLK** [comment]
I think we could probably just delete the old guides.

**Comment by lmichael107** [comment]
merge? actions?

**Comment by jmvera255** [comment]
> merge? actions?

yes! was on my to-do list, thanks for the ping

**Pull request merged**
